export const chartData = [
    { label: "Angular", value: 9 },
    { label: "ASP.NET C#", value: 10 },
    { label: "React", value: 10 },
    { label: "Typescript", value: 10 },
    { label: "HTML", value: 8 },
    { label: "Javascript", value: 8 },
    { label: "CSS", value: 9 },
    { label: "Node.js", value: 7 },
    { label: "C++", value: 4 },
    { label: "C", value: 6 },
    { label: "VHDL", value: 3 },
    { label: "Postgresql", value: 8 },
    { label: "MongoDB", value: 8 },
    { label: "Java", value: 7 },
    { label: "AWS", value: 8 },
    { label: "Unity", value: 6 },
    { label: "Blender", value: 5 },
    { label: "Figma", value: 6 },
    { label: "Git", value: 7 },
    { label: "Python", value: 2 },
  ];
  