export const education = [
  {
    summary:
      "The phenomenal pace of change in this field makes it impossible to provide a lasting professional education based on technology alone; a Bachelor of Engineering (Honours) in Computer Systems Engineering is therefore geared to provide core skills and theoretical knowledge needed for a future-proofed approach",
    type: "Bachelors Degree",
    name: "University of Auckland",
    nameShort: "UoA",
    position: "Computer Systems Engineering Student",
    dateString: "March 2018 - November 2022",
    startDate: "March 2018",
    endDate: "November 2022",
    technologies: [
      "React",
      "CSS",
      "HTML",
      "Typescript",
      "Java",
      "C++",
      "C",
      "Matlab",
      "R",
      "Python",
      "VHDL",
      "Android Studio",
    ],
    website:
      "https://www.auckland.ac.nz/en/study/study-options/find-a-study-option/computer-systems-engineering.html",
  },
  {
    summary:
      "This bootcamp was an intense software development course that involved 800 hours of development work. This was where I gained a large portion of my foundational skills as a software developer.",
    type: "Bootcamp",
    name: "Enspiral Dev Academy",
    nameShort: "EDA",
    position: "Fullstack Web Development Student",
    dateString: "March 2020 - June 2020 (800 hours)",
    technologies: [
      "Javascript",
      "jQuery",
      "React.js",
      "Redux",
      "REST APIs",
      "Jest",
      "Postman",
      "Supertest",
      "Superagent",
      "Passport.js",
      "HTML",
      "CSS",
      "Handlebars",
      "Node.js",
      "Express.js",
      "Knex.js",
      "Github",
      "AdobeXD",
      "Photoshop",
    ],
    website: "https://devacademy.co.nz/",
  },
];
